---

dontChroot: false
skip_if_no_internet: false
update_db: true

pacman:
	num_retries: 1
	disable_download_timeout: true
	
script:
    - command: "pacman-key --init"
    - command: "pacman-key --populate"
