
    name: "Configuration Setup and Clean Up tasks..."

dontChroot: false

# timeout: 999

script:
    - command: "Echo Hello world, postinstall working!"
    timeout: 5
    - command: "/usr/local/bin/postinstall.sh"
    timeout: 600
#    - command: "pacman-key --init"
#    timeout: 300
#    - command: "pacman-key --populate"
#    timeout: 300
#    - command: "pacman -Syy"
#    timeout: 50

