---

dontChroot: false

script:
    - command: "name=$(ls -1 /home)"
    - command: "mkdir -p /home/$name/.config"
    - command: "mkdir -p /home/$name/.config/nemo"
    - command: "mkdir -p /home/$name/.local/share/cinnamon/extensions"
    - command: "cp -r /cinnamon-configs/cinnamon-stuff/.config/* /home/$name/.config/"
    - command: "mkdir -p /home/$name/.config/autostart"
    - command: "cp -r /cinnamon-configs/dd.desktop /home/$name/.config/autostart"
    - command: "chown -R $name:$name /home/$name/.config"
    - command: "chown -R $name:$name /middle.png"
    - command: "cp -r /cinnamon-configs/.bashrc /home/$name/.bashrc"
    - command: "cp -r /cinnamon-configs/.bashrc /root"
    - command: "cp -r /cinnamon-configs/AcreetionOS.txt /root"
    - command: "cp -r /cinnamon-configs/AcreetionOS.txt /home/$name/AcreetionOS.txt"
    - command: "mv /resolv.conf /etc/resolv.conf"
    - command: "chattr +i /etc/resolv.conf"
    - command: "chattr +i /etc/os-release"
    - command: "cp /cinnamon-configs/AcreetionOS.txt /home/$name/"
    - command: "mkdir -p /usr/share/backgrounds"
    - command: "cp -r /backgrounds /usr/share/backgrounds"
    - command: "rm -rf /backgrounds"
    - command: "chsh -s /bin/bash root"
    - command: 'echo "Defaults pwfeedback" | sudo EDITOR=''tee -a'' visudo >/dev/null 2>&1'
    - command: "cp /mkinitcpio/mkinitcpio.conf /etc/mkinitcpio.conf"
    - command: "cp /mkinitcpio/archiso.conf /etc/mkinitcpio.conf.d"
    - command: "cp /cinnamon-configs/.nanorc /home/$name/.nanorc"
    - command: "rm -rf /mkinitcpio"
    - command: "rm -rf cinnamon-configs"
