---

dontChroot: false

script:
    - command: "mkdir -p /home/${user}/.config"
    - command: "mkdir -p /home/${user}/.config/nemo"
    - command: "mkdir -p /home/${user}/.local/share/cinnamon/extensions"
    - command: "cp -r /cinnamon-configs/cinnamon-stuff/.config/* /home/${user}/.config/"
    - command: "mkdir -p /home/${user}/.config/autostart"
    - command: "cp -r /cinnamon-configs/dd.desktop /home/${user}/.config/autostart"
    - command: "chown -R ${user}:${user} /home/${user}/.config"
    - command: "chown -R ${user}:${user} /middle.png"
    - command: "cp -r /cinnamon-configs/.bashrc /home/${user}/.bashrc"
    - command: "cp -r /cinnamon-configs/.bashrc /root"
    - command: "cp -r /cinnamon-configs/AcreetionOS.txt /root"
    - command: "cp -r /cinnamon-configs/AcreetionOS.txt /home/${user}/AcreetionOS.txt"
    - command: "mv /resolv.conf /etc/resolv.conf"
    - command: "chattr +i /etc/resolv.conf"
    - command: "chattr +i /etc/os-release"
    - command: "cp /cinnamon-configs/AcreetionOS.txt /home/${user}/"
    - command: "mkdir -p /usr/share/backgrounds"
    - command: "cp -r /backgrounds /usr/share/backgrounds"
    - command: "rm -rf /backgrounds"
    - command: "chsh -s /bin/bash root"
    - command: 'echo "Defaults pwfeedback" | sudo EDITOR=''tee -a'' visudo >/dev/null 2>&1'
    - command: "cp /mkinitcpio/mkinitcpio.conf /etc/mkinitcpio.conf"
    - command: "cp /mkinitcpio/archiso.conf /etc/mkinitcpio.conf.d"
    - command: "cp /cinnamon-configs/.nanorc /home/${user}/.nanorc"
    - command: "rm -rf /mkinitcpio"
    - command: "rm -rf cinnamon-configs"
